class Country {
  final String code;
  final String name;
  final String dial;
  final String flag;

  const Country({required this.code, required this.name, required this.dial, required this.flag});
}

const List<Country> kCountries = [
  Country(code: 'ET', name: 'Ethiopia', dial: '+251', flag: '🇪🇹'),
  Country(code: 'KE', name: 'Kenya', dial: '+254', flag: '🇰🇪'),
  Country(code: 'DJ', name: 'Djibouti', dial: '+253', flag: '🇩🇯'),
  Country(code: 'SO', name: 'Somalia', dial: '+252', flag: '🇸🇴'),
  Country(code: 'SD', name: 'Sudan', dial: '+249', flag: '🇸🇩'),
  Country(code: 'SS', name: 'South Sudan', dial: '+211', flag: '🇸🇸'),
  Country(code: 'ER', name: 'Eritrea', dial: '+291', flag: '🇪🇷'),
  Country(code: 'UG', name: 'Uganda', dial: '+256', flag: '🇺🇬'),
  Country(code: 'TZ', name: 'Tanzania', dial: '+255', flag: '🇹🇿'),
  Country(code: 'RW', name: 'Rwanda', dial: '+250', flag: '🇷🇼'),
  Country(code: 'US', name: 'United States', dial: '+1', flag: '🇺🇸'),
  Country(code: 'GB', name: 'United Kingdom', dial: '+44', flag: '🇬🇧'),
  Country(code: 'CA', name: 'Canada', dial: '+1', flag: '🇨🇦'),
  Country(code: 'AE', name: 'United Arab Emirates', dial: '+971', flag: '🇦🇪'),
  Country(code: 'SA', name: 'Saudi Arabia', dial: '+966', flag: '🇸🇦'),
  Country(code: 'QA', name: 'Qatar', dial: '+974', flag: '🇶🇦'),
  Country(code: 'KW', name: 'Kuwait', dial: '+965', flag: '🇰🇼'),
  Country(code: 'BH', name: 'Bahrain', dial: '+973', flag: '🇧🇭'),
  Country(code: 'OM', name: 'Oman', dial: '+968', flag: '🇴🇲'),
  Country(code: 'IN', name: 'India', dial: '+91', flag: '🇮🇳'),
  Country(code: 'CN', name: 'China', dial: '+86', flag: '🇨🇳'),
  Country(code: 'DE', name: 'Germany', dial: '+49', flag: '🇩🇪'),
  Country(code: 'FR', name: 'France', dial: '+33', flag: '🇫🇷'),
  Country(code: 'IT', name: 'Italy', dial: '+39', flag: '🇮🇹'),
  Country(code: 'ES', name: 'Spain', dial: '+34', flag: '🇪🇸'),
  Country(code: 'NL', name: 'Netherlands', dial: '+31', flag: '🇳🇱'),
  Country(code: 'SE', name: 'Sweden', dial: '+46', flag: '🇸🇪'),
  Country(code: 'NO', name: 'Norway', dial: '+47', flag: '🇳🇴'),
  Country(code: 'AU', name: 'Australia', dial: '+61', flag: '🇦🇺'),
  Country(code: 'JP', name: 'Japan', dial: '+81', flag: '🇯🇵'),
  Country(code: 'ZA', name: 'South Africa', dial: '+27', flag: '🇿🇦'),
  Country(code: 'EG', name: 'Egypt', dial: '+20', flag: '🇪🇬'),
  Country(code: 'NG', name: 'Nigeria', dial: '+234', flag: '🇳🇬'),
  Country(code: 'GH', name: 'Ghana', dial: '+233', flag: '🇬🇭'),
  Country(code: 'AF', name: 'Afghanistan', dial: '+93', flag: '🇦🇫'),
  Country(code: 'AL', name: 'Albania', dial: '+355', flag: '🇦🇱'),
  Country(code: 'DZ', name: 'Algeria', dial: '+213', flag: '🇩🇿'),
  Country(code: 'AD', name: 'Andorra', dial: '+376', flag: '🇦🇩'),
  Country(code: 'AO', name: 'Angola', dial: '+244', flag: '🇦🇴'),
  Country(code: 'AG', name: 'Antigua and Barbuda', dial: '+1', flag: '🇦🇬'),
  Country(code: 'AR', name: 'Argentina', dial: '+54', flag: '🇦🇷'),
  Country(code: 'AM', name: 'Armenia', dial: '+374', flag: '🇦🇲'),
  Country(code: 'AT', name: 'Austria', dial: '+43', flag: '🇦🇹'),
  Country(code: 'AZ', name: 'Azerbaijan', dial: '+994', flag: '🇦🇿'),
  Country(code: 'BS', name: 'Bahamas', dial: '+1', flag: '🇧🇸'),
  Country(code: 'BD', name: 'Bangladesh', dial: '+880', flag: '🇧🇩'),
  Country(code: 'BB', name: 'Barbados', dial: '+1', flag: '🇧🇧'),
  Country(code: 'BY', name: 'Belarus', dial: '+375', flag: '🇧🇾'),
  Country(code: 'BE', name: 'Belgium', dial: '+32', flag: '🇧🇪'),
  Country(code: 'BZ', name: 'Belize', dial: '+501', flag: '🇧🇿'),
  Country(code: 'BJ', name: 'Benin', dial: '+229', flag: '🇧🇯'),
  Country(code: 'BT', name: 'Bhutan', dial: '+975', flag: '🇧🇹'),
  Country(code: 'BO', name: 'Bolivia', dial: '+591', flag: '🇧🇴'),
  Country(code: 'BA', name: 'Bosnia and Herzegovina', dial: '+387', flag: '🇧🇦'),
  Country(code: 'BW', name: 'Botswana', dial: '+267', flag: '🇧🇼'),
  Country(code: 'BR', name: 'Brazil', dial: '+55', flag: '🇧🇷'),
  Country(code: 'BN', name: 'Brunei', dial: '+673', flag: '🇧🇳'),
  Country(code: 'BG', name: 'Bulgaria', dial: '+359', flag: '🇧🇬'),
  Country(code: 'BF', name: 'Burkina Faso', dial: '+226', flag: '🇧🇫'),
  Country(code: 'BI', name: 'Burundi', dial: '+257', flag: '🇧🇮'),
  Country(code: 'KH', name: 'Cambodia', dial: '+855', flag: '🇰🇭'),
  Country(code: 'CM', name: 'Cameroon', dial: '+237', flag: '🇨🇲'),
  Country(code: 'CV', name: 'Cape Verde', dial: '+238', flag: '🇨🇻'),
  Country(code: 'CF', name: 'Central African Republic', dial: '+236', flag: '🇨🇫'),
  Country(code: 'TD', name: 'Chad', dial: '+235', flag: '🇹🇩'),
  Country(code: 'CL', name: 'Chile', dial: '+56', flag: '🇨🇱'),
  Country(code: 'CO', name: 'Colombia', dial: '+57', flag: '🇨🇴'),
  Country(code: 'KM', name: 'Comoros', dial: '+269', flag: '🇰🇲'),
  Country(code: 'CR', name: 'Costa Rica', dial: '+506', flag: '🇨🇷'),
  Country(code: 'HR', name: 'Croatia', dial: '+385', flag: '🇭🇷'),
  Country(code: 'CU', name: 'Cuba', dial: '+53', flag: '🇨🇺'),
  Country(code: 'CY', name: 'Cyprus', dial: '+357', flag: '🇨🇾'),
  Country(code: 'CZ', name: 'Czech Republic', dial: '+420', flag: '🇨🇿'),
  Country(code: 'CD', name: 'DR Congo', dial: '+243', flag: '🇨🇩'),
  Country(code: 'DK', name: 'Denmark', dial: '+45', flag: '🇩🇰'),
  Country(code: 'DM', name: 'Dominica', dial: '+1', flag: '🇩🇲'),
  Country(code: 'DO', name: 'Dominican Republic', dial: '+1', flag: '🇩🇴'),
  Country(code: 'TL', name: 'East Timor', dial: '+670', flag: '🇹🇱'),
  Country(code: 'EC', name: 'Ecuador', dial: '+593', flag: '🇪🇨'),
  Country(code: 'SV', name: 'El Salvador', dial: '+503', flag: '🇸🇻'),
  Country(code: 'GQ', name: 'Equatorial Guinea', dial: '+240', flag: '🇬🇶'),
  Country(code: 'EE', name: 'Estonia', dial: '+372', flag: '🇪🇪'),
  Country(code: 'FJ', name: 'Fiji', dial: '+679', flag: '🇫🇯'),
  Country(code: 'FI', name: 'Finland', dial: '+358', flag: '🇫🇮'),
  Country(code: 'GA', name: 'Gabon', dial: '+241', flag: '🇬🇦'),
  Country(code: 'GM', name: 'Gambia', dial: '+220', flag: '🇬🇲'),
  Country(code: 'GE', name: 'Georgia', dial: '+995', flag: '🇬🇪'),
  Country(code: 'GR', name: 'Greece', dial: '+30', flag: '🇬🇷'),
  Country(code: 'GD', name: 'Grenada', dial: '+1', flag: '🇬🇩'),
  Country(code: 'GT', name: 'Guatemala', dial: '+502', flag: '🇬🇹'),
  Country(code: 'GN', name: 'Guinea', dial: '+224', flag: '🇬🇳'),
  Country(code: 'GW', name: 'Guinea-Bissau', dial: '+245', flag: '🇬🇼'),
  Country(code: 'GY', name: 'Guyana', dial: '+592', flag: '🇬🇾'),
  Country(code: 'HT', name: 'Haiti', dial: '+509', flag: '🇭🇹'),
  Country(code: 'HN', name: 'Honduras', dial: '+504', flag: '🇭🇳'),
  Country(code: 'HK', name: 'Hong Kong', dial: '+852', flag: '🇭🇰'),
  Country(code: 'HU', name: 'Hungary', dial: '+36', flag: '🇭🇺'),
  Country(code: 'IS', name: 'Iceland', dial: '+354', flag: '🇮🇸'),
  Country(code: 'ID', name: 'Indonesia', dial: '+62', flag: '🇮🇩'),
  Country(code: 'IR', name: 'Iran', dial: '+98', flag: '🇮🇷'),
  Country(code: 'IQ', name: 'Iraq', dial: '+964', flag: '🇮🇶'),
  Country(code: 'IE', name: 'Ireland', dial: '+353', flag: '🇮🇪'),
  Country(code: 'IL', name: 'Israel', dial: '+972', flag: '🇮🇱'),
  Country(code: 'CI', name: 'Ivory Coast', dial: '+225', flag: '🇨🇮'),
  Country(code: 'JM', name: 'Jamaica', dial: '+1', flag: '🇯🇲'),
  Country(code: 'JO', name: 'Jordan', dial: '+962', flag: '🇯🇴'),
  Country(code: 'KZ', name: 'Kazakhstan', dial: '+7', flag: '🇰🇿'),
  Country(code: 'KG', name: 'Kyrgyzstan', dial: '+996', flag: '🇰🇬'),
  Country(code: 'LA', name: 'Laos', dial: '+856', flag: '🇱🇦'),
  Country(code: 'LV', name: 'Latvia', dial: '+371', flag: '🇱🇻'),
  Country(code: 'LB', name: 'Lebanon', dial: '+961', flag: '🇱🇧'),
  Country(code: 'LS', name: 'Lesotho', dial: '+266', flag: '🇱🇸'),
  Country(code: 'LR', name: 'Liberia', dial: '+231', flag: '🇱🇷'),
  Country(code: 'LY', name: 'Libya', dial: '+218', flag: '🇱🇾'),
  Country(code: 'LI', name: 'Liechtenstein', dial: '+423', flag: '🇱🇮'),
  Country(code: 'LT', name: 'Lithuania', dial: '+370', flag: '🇱🇹'),
  Country(code: 'LU', name: 'Luxembourg', dial: '+352', flag: '🇱🇺'),
  Country(code: 'MO', name: 'Macau', dial: '+853', flag: '🇲🇴'),
  Country(code: 'MK', name: 'North Macedonia', dial: '+389', flag: '🇲🇰'),
  Country(code: 'MG', name: 'Madagascar', dial: '+261', flag: '🇲🇬'),
  Country(code: 'MW', name: 'Malawi', dial: '+265', flag: '🇲🇼'),
  Country(code: 'MY', name: 'Malaysia', dial: '+60', flag: '🇲🇾'),
  Country(code: 'MV', name: 'Maldives', dial: '+960', flag: '🇲🇻'),
  Country(code: 'ML', name: 'Mali', dial: '+223', flag: '🇲🇱'),
  Country(code: 'MT', name: 'Malta', dial: '+356', flag: '🇲🇹'),
  Country(code: 'MR', name: 'Mauritania', dial: '+222', flag: '🇲🇷'),
  Country(code: 'MU', name: 'Mauritius', dial: '+230', flag: '🇲🇺'),
  Country(code: 'MX', name: 'Mexico', dial: '+52', flag: '🇲🇽'),
  Country(code: 'MD', name: 'Moldova', dial: '+373', flag: '🇲🇩'),
  Country(code: 'MC', name: 'Monaco', dial: '+377', flag: '🇲🇨'),
  Country(code: 'MN', name: 'Mongolia', dial: '+976', flag: '🇲🇳'),
  Country(code: 'ME', name: 'Montenegro', dial: '+382', flag: '🇲🇪'),
  Country(code: 'MA', name: 'Morocco', dial: '+212', flag: '🇲🇦'),
  Country(code: 'MZ', name: 'Mozambique', dial: '+258', flag: '🇲🇿'),
  Country(code: 'MM', name: 'Myanmar', dial: '+95', flag: '🇲🇲'),
  Country(code: 'NA', name: 'Namibia', dial: '+264', flag: '🇳🇦'),
  Country(code: 'NP', name: 'Nepal', dial: '+977', flag: '🇳🇵'),
  Country(code: 'NZ', name: 'New Zealand', dial: '+64', flag: '🇳🇿'),
  Country(code: 'NI', name: 'Nicaragua', dial: '+505', flag: '🇳🇮'),
  Country(code: 'NE', name: 'Niger', dial: '+227', flag: '🇳🇪'),
  Country(code: 'KP', name: 'North Korea', dial: '+850', flag: '🇰🇵'),
  Country(code: 'PK', name: 'Pakistan', dial: '+92', flag: '🇵🇰'),
  Country(code: 'PS', name: 'Palestine', dial: '+970', flag: '🇵🇸'),
  Country(code: 'PA', name: 'Panama', dial: '+507', flag: '🇵🇦'),
  Country(code: 'PG', name: 'Papua New Guinea', dial: '+675', flag: '🇵🇬'),
  Country(code: 'PY', name: 'Paraguay', dial: '+595', flag: '🇵🇾'),
  Country(code: 'PE', name: 'Peru', dial: '+51', flag: '🇵🇪'),
  Country(code: 'PH', name: 'Philippines', dial: '+63', flag: '🇵🇭'),
  Country(code: 'PL', name: 'Poland', dial: '+48', flag: '🇵🇱'),
  Country(code: 'PT', name: 'Portugal', dial: '+351', flag: '🇵🇹'),
  Country(code: 'PR', name: 'Puerto Rico', dial: '+1', flag: '🇵🇷'),
  Country(code: 'CG', name: 'Republic of the Congo', dial: '+242', flag: '🇨🇬'),
  Country(code: 'RO', name: 'Romania', dial: '+40', flag: '🇷🇴'),
  Country(code: 'RU', name: 'Russia', dial: '+7', flag: '🇷🇺'),
  Country(code: 'WS', name: 'Samoa', dial: '+685', flag: '🇼🇸'),
  Country(code: 'SM', name: 'San Marino', dial: '+378', flag: '🇸🇲'),
  Country(code: 'SN', name: 'Senegal', dial: '+221', flag: '🇸🇳'),
  Country(code: 'RS', name: 'Serbia', dial: '+381', flag: '🇷🇸'),
  Country(code: 'SC', name: 'Seychelles', dial: '+248', flag: '🇸🇨'),
  Country(code: 'SL', name: 'Sierra Leone', dial: '+232', flag: '🇸🇱'),
  Country(code: 'SG', name: 'Singapore', dial: '+65', flag: '🇸🇬'),
  Country(code: 'SK', name: 'Slovakia', dial: '+421', flag: '🇸🇰'),
  Country(code: 'SI', name: 'Slovenia', dial: '+386', flag: '🇸🇮'),
  Country(code: 'SB', name: 'Solomon Islands', dial: '+677', flag: '🇸🇧'),
  Country(code: 'KR', name: 'South Korea', dial: '+82', flag: '🇰🇷'),
  Country(code: 'LK', name: 'Sri Lanka', dial: '+94', flag: '🇱🇰'),
  Country(code: 'SR', name: 'Suriname', dial: '+597', flag: '🇸🇷'),
  Country(code: 'SZ', name: 'Eswatini', dial: '+268', flag: '🇸🇿'),
  Country(code: 'CH', name: 'Switzerland', dial: '+41', flag: '🇨🇭'),
  Country(code: 'SY', name: 'Syria', dial: '+963', flag: '🇸🇾'),
  Country(code: 'TW', name: 'Taiwan', dial: '+886', flag: '🇹🇼'),
  Country(code: 'TJ', name: 'Tajikistan', dial: '+992', flag: '🇹🇯'),
  Country(code: 'TH', name: 'Thailand', dial: '+66', flag: '🇹🇭'),
  Country(code: 'TG', name: 'Togo', dial: '+228', flag: '🇹🇬'),
  Country(code: 'TT', name: 'Trinidad and Tobago', dial: '+1', flag: '🇹🇹'),
  Country(code: 'TN', name: 'Tunisia', dial: '+216', flag: '🇹🇳'),
  Country(code: 'TR', name: 'Turkey', dial: '+90', flag: '🇹🇷'),
  Country(code: 'TM', name: 'Turkmenistan', dial: '+993', flag: '🇹🇲'),
  Country(code: 'UA', name: 'Ukraine', dial: '+380', flag: '🇺🇦'),
  Country(code: 'UY', name: 'Uruguay', dial: '+598', flag: '🇺🇾'),
  Country(code: 'UZ', name: 'Uzbekistan', dial: '+998', flag: '🇺🇿'),
  Country(code: 'VE', name: 'Venezuela', dial: '+58', flag: '🇻🇪'),
  Country(code: 'VN', name: 'Vietnam', dial: '+84', flag: '🇻🇳'),
  Country(code: 'YE', name: 'Yemen', dial: '+967', flag: '🇾🇪'),
  Country(code: 'ZM', name: 'Zambia', dial: '+260', flag: '🇿🇲'),
  Country(code: 'ZW', name: 'Zimbabwe', dial: '+263', flag: '🇿🇼'),
];

const Country kDefaultCountry = Country(code: 'ET', name: 'Ethiopia', dial: '+251', flag: '🇪🇹');

Country findCountryByDial(String? dial) {
  if (dial == null || dial.isEmpty) return kDefaultCountry;
  return kCountries.firstWhere(
    (c) => c.dial == dial,
    orElse: () => kDefaultCountry,
  );
}

/// Normalize a raw phone input to E.164. Mirrors app/Support/PhoneNumber.php.
String? normalizePhone(String? input, {String countryDial = '+251'}) {
  if (input == null) return null;
  final trimmed = input.trim();
  if (trimmed.isEmpty) return null;

  final hasPlus = trimmed.startsWith('+');
  var digits = trimmed.replaceAll(RegExp(r'\D+'), '');
  if (digits.isEmpty) return null;

  if (hasPlus) return '+$digits';

  digits = digits.replaceFirst(RegExp(r'^0+'), '');
  if (digits.isEmpty) return null;

  final cc = countryDial.trim().startsWith('+')
      ? countryDial.trim()
      : '+${countryDial.replaceAll(RegExp(r'\D+'), '')}';

  return '$cc$digits';
}
