// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAziEJ4r9o06gOMjyo5TfofKvf6JphDyPc',
    appId: '1:989314767379:web:0fa3ad674311aa351e3de6',
    messagingSenderId: '989314767379',
    projectId: 'lidu-c46e0',
    authDomain: 'lidu-c46e0.firebaseapp.com',
    storageBucket: 'lidu-c46e0.firebasestorage.app',
    measurementId: 'G-TQLCFFQ7H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUiBb3oDSYk7rQuc6KNdpIxaCl6fqTQpM',
    appId: '1:989314767379:android:4a3829ab950e0a5e1e3de6',
    messagingSenderId: '989314767379',
    projectId: 'lidu-c46e0',
    storageBucket: 'lidu-c46e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAlxU4e8z8a3MHzLKX0szh4Sa_KedJno',
    appId: '1:989314767379:ios:6611a4a2354623831e3de6',
    messagingSenderId: '989314767379',
    projectId: 'lidu-c46e0',
    storageBucket: 'lidu-c46e0.firebasestorage.app',
    iosBundleId: 'com.fisha.guestWishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAlxU4e8z8a3MHzLKX0szh4Sa_KedJno',
    appId: '1:989314767379:ios:6611a4a2354623831e3de6',
    messagingSenderId: '989314767379',
    projectId: 'lidu-c46e0',
    storageBucket: 'lidu-c46e0.firebasestorage.app',
    iosBundleId: 'com.fisha.guestWishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAziEJ4r9o06gOMjyo5TfofKvf6JphDyPc',
    appId: '1:989314767379:web:e581f77e81d103191e3de6',
    messagingSenderId: '989314767379',
    projectId: 'lidu-c46e0',
    authDomain: 'lidu-c46e0.firebaseapp.com',
    storageBucket: 'lidu-c46e0.firebasestorage.app',
    measurementId: 'G-6QXRXE29KV',
  );
}
