import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:guest_wish_app/Utils/brandColor.dart';

// NOTE: In a real Flutter project, the 'firebase_options.dart' file is generated
// by the 'flutterfire configure' command and contains your specific keys.
// For this environment, we rely on the platform to link the config.
import 'firebase_options.dart'; 

// -----------------------------------------------------------------------------
// 1. ENVIRONMENT/GLOBAL VARIABLES
// These variables are provided by the Canvas environment for application scoping.
// -----------------------------------------------------------------------------
// The following variables are expected to be available at runtime in the Canvas
// environment. For local testing, ensure your FlutterFire configuration is complete.
const String __app_id = 'flutter-wedding-wishes-12345';
const String __initial_auth_token = ''; // Use custom token or empty for anonymous

// -----------------------------------------------------------------------------
// 2. MAIN FUNCTION AND APP WIDGET
// -----------------------------------------------------------------------------
void main() async {
  // Ensure Flutter is initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the options generated by FlutterFire CLI
  // This is crucial for running on Flutter Web, iOS, or Android.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  runApp(const WishApp());
}

class WishApp extends StatelessWidget {
  const WishApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Wishes Guestbook',
      // Using Inter and Playfair Display for an elegant look
      theme: ThemeData(
        primarySwatch: Colors.pink,
        scaffoldBackgroundColor: backgroundColor, // Soft Pink Background
        textTheme: GoogleFonts.interTextTheme(
          Theme.of(context).textTheme,
        ),
      ),
      home: const WishHomePage(),
    );
  }
}

// -----------------------------------------------------------------------------
// 3. HOME PAGE STATEFUL WIDGET
// -----------------------------------------------------------------------------
class WishHomePage extends StatefulWidget {
  const WishHomePage({super.key});

  @override
  State<WishHomePage> createState() => _WishHomePageState();
}

class _WishHomePageState extends State<WishHomePage> {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _messageController = TextEditingController();
  String _userId = 'anonymous';
  bool _isLoading = true;
  String? _error;

  // Defines the public collection path for shared, collaborative data
  late final CollectionReference _wishesRef;

  @override
  void initState() {
    super.initState();
    // Path structure: /artifacts/{appId}/public/data/{your_collection_name}
    _wishesRef = _db.collection('artifacts/${__app_id}/public/data/weddingWishes');
    _initializeAuthAndLoad();
  }

  @override
  void dispose() {
    _nameController.dispose();
    _messageController.dispose();
    super.dispose();
  }

  // Authentication and Initialization Logic
  Future<void> _initializeAuthAndLoad() async {
    setState(() {
      _isLoading = true;
    });
    try {
      // Authenticate using custom token or anonymously
      if (__initial_auth_token.isNotEmpty) {
        await _auth.signInWithCustomToken(__initial_auth_token);
      } else {
        await _auth.signInAnonymously();
      }

      // Get the current user's UID
      _userId = _auth.currentUser?.uid ?? 'unknown';
    } on FirebaseException catch (e) {
      _error = 'Firebase Auth Error: ${e.message}';
      print('Auth Error: $_error');
    } catch (e) {
      _error = 'Initialization Error: $e';
      print('Init Error: $_error');
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  // Function to add a new wish to Firestore
  Future<void> _addWish() async {
    final name = _nameController.text.trim();
    final message = _messageController.text.trim();

    if (name.isEmpty || message.isEmpty) {
      setState(() {
        _error = "Please enter both your name and a message.";
      });
      return;
    }

    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      await _wishesRef.add({
        'name': name,
        'message': message,
        'timestamp': FieldValue.serverTimestamp(),
        'userId': _userId,
      });

      // Clear the text fields
      _nameController.clear();
      _messageController.clear();
    } on FirebaseException catch (e) {
      setState(() {
        _error = 'Failed to submit wish: ${e.message}';
      });
      print('Firestore Error: $_error');
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  // ---------------------------------------------------------------------------
  // 4. UI BUILD METHOD
  // ---------------------------------------------------------------------------
  @override
  Widget build(BuildContext context) {
    if (_isLoading && _auth.currentUser == null) {
      return const Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CircularProgressIndicator(color: Colors.pink),
              SizedBox(height: 16),
              Text('Signing in and loading...', style: TextStyle(color: Colors.pink)),
            ],
          ),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Wishes Guestbook',
          style: GoogleFonts.playfairDisplay(
            fontWeight: FontWeight.bold,
            color: primaryColor,
          ),
        ),
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 4,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 800),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                // Header Details
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(16),
                    boxShadow: [
                      BoxShadow(
                        color: Colors.pink.shade50.withOpacity(0.5),
                        blurRadius: 10,
                        offset: const Offset(0, 5),
                      ),
                    ],
                  ),
                  child: Column(
                    children: [
                      Text(
                        'Leave Your best wishes or any messages',
                        style: TextStyle(
                          fontSize: 18,
                          color: Colors.grey.shade600,
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),

                // Wish Submission Form
                _buildWishForm(),
                const SizedBox(height: 32),

                // Wishes Display Area
                _buildWishList(),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildWishForm() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [Colors.white, backgroundColor],
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: backgroundColor, width: 1),
        boxShadow: const [
          BoxShadow(
            color: Colors.black12,
            blurRadius: 20,
            offset: Offset(0, 10),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: [
              Icon(Icons.favorite, color: primaryColor, size: 24),
              const SizedBox(width: 8),
              Text(
                'Share Your Love',
                style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.bold,
                  color: primaryColor,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          // Name Input
          TextField(
            controller: _nameController,
            decoration: InputDecoration(
              hintText: 'Your Name (e.g., Aunt Samri)',
              filled: true,
              fillColor: Colors.white,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: borderColor),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: borderColor),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: borderColor, width: 2),
              ),
            ),
          ),
          const SizedBox(height: 16),
          // Message Input
          TextField(
            controller: _messageController,
            maxLines: 4,
            decoration: InputDecoration(
              hintText: 'Write your heartfelt wish or advice here...',
              filled: true,
              fillColor: Colors.white,
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: borderColor),
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: borderColor),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide(color: borderColor, width: 2),
              ),
            ),
          ),
          if (_error != null)
            Padding(
              padding: const EdgeInsets.only(top: 16.0),
              child: Text(
                _error!,
                style: const TextStyle(color: primaryColor, fontWeight: FontWeight.bold),
              ),
            ),
          const SizedBox(height: 20),
          // Submit Button
          Align(
            alignment: Alignment.centerRight,
            child: ElevatedButton.icon(
              onPressed: _isLoading ? null : _addWish,
              icon: _isLoading
                  ? const SizedBox(
                      width: 18,
                      height: 18,
                      child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                    )
                  : const Icon(Icons.send),
              label: Text(_isLoading ? 'Sending...' : 'Submit Wish'),
              style: ElevatedButton.styleFrom(
                foregroundColor: Colors.white,
                backgroundColor: primaryColor,
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(30),
                ),
                textStyle: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                elevation: 8,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildWishList() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Wishes from Our Loved Ones',
          style: TextStyle(
            fontSize: 22,
            fontWeight: FontWeight.bold,
            color: Colors.grey.shade700,
          ),
        ),
        const Divider(color: primaryColor),
        const SizedBox(height: 16),

        // StreamBuilder to listen for real-time changes
        StreamBuilder<QuerySnapshot>(
          stream: _wishesRef.orderBy('timestamp', descending: true).snapshots(),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(
                child: Padding(
                  padding: EdgeInsets.all(24.0),
                  child: CircularProgressIndicator(color: borderColor),
                ),
              );
            }
            if (snapshot.hasError) {
              return Center(child: Text('Error loading wishes: ${snapshot.error}'));
            }
            if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
              return Center(
                child: Container(
                  padding: const EdgeInsets.all(24),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: Colors.pink.shade100),
                  ),
                  child: Text(
                    'Be the first to leave a wish!',
                    style: TextStyle(fontSize: 16, fontStyle: FontStyle.italic, color: Colors.grey.shade500),
                  ),
                ),
              );
            }

            final wishes = snapshot.data!.docs;

            return GridView.builder(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              // Use a single column for a list-like view
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 1, 
                childAspectRatio: 3.5, // Adjust height
                mainAxisSpacing: 16,
                crossAxisSpacing: 16,
              ),
              itemCount: wishes.length,
              itemBuilder: (context, index) {
                final data = wishes[index].data() as Map<String, dynamic>;
                return WishCard(
                  name: data['name'] ?? 'Anonymous',
                  message: data['message'] ?? 'No message.',
                  timestamp: data['timestamp'],
                );
              },
            );
          },
        ),
      ],
    );
  }
}

// -----------------------------------------------------------------------------
// 5. WISH CARD WIDGET
// -----------------------------------------------------------------------------
class WishCard extends StatelessWidget {
  final String name;
  final String message;
  final Timestamp? timestamp;

  const WishCard({
    super.key,
    required this.name,
    required this.message,
    this.timestamp,
  });

  @override
  Widget build(BuildContext context) {
    String formattedTime = 'Moment Ago';
    if (timestamp != null) {
      DateTime date = timestamp!.toDate();
      formattedTime = '${date.month}/${date.day}/${date.year}';
    }

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        // Pink border top for visual flair
        border: Border(top: BorderSide(color: borderColor, width: 4)),
        boxShadow: const [
          BoxShadow(
            color: Colors.black12,
            blurRadius: 8,
            offset: Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Expanded(
            child: Text(
              '"$message"',
              style: TextStyle(
                fontSize: 16,
                fontStyle: FontStyle.italic,
                color: Colors.grey.shade700,
              ),
              overflow: TextOverflow.ellipsis,
              maxLines: 2,
            ),
          ),
          const Divider(height: 16, thickness: 1, color: Colors.grey),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              Row(
                children: [
                  Icon(Icons.favorite, size: 16, color: primaryColor),
                  const SizedBox(width: 4),
                  Text(
                    name,
                    style: TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.bold,
                      color: primaryColor,
                    ),
                  ),
                ],
              ),
              Text(
                formattedTime,
                style: TextStyle(
                  fontSize: 12,
                  color: Colors.grey.shade500,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
